### PR TITLE
Add donate via PayPal button

### LINKED ISSUE #918: Add donation link to README file
**FEATURE**

Add a Donation link to the README file

**REASONING**

Allow users of this project to show appreciation and support to the creator and maintainers.

This isn't an attempt to monetise the projects, its purely for those who want to support the work done here.

### PR DESCRIPTION
**Pull request by jerome-h-dev**
**Resolves #918** 

**NOTE** 
Requires a valid PayPal link to replace `https://example.com` placeholder 

**PREVIEW**
Screenshot 2023-11-23 at 11 56 18

### CODE REVIEW

**Comment by jerome-h-dev** [comment]
Happy to add link to PR if provided

**Comment by ChristopherHX** [comment]
Only individual paypal links can be found across this project.

- MCMrarm/mrarm (Admin) The creator and maintainer till mid 2020 (paypal link documented there https://github.com/MCMrARM/mbp2018-bridge-drv/blob/b43fcc069da73e051072fde24af4014c9c487286/README.md?plain=1#L11)
- Me (Admin) current Maintainer, initial experimental 64bit ports are from my side 2019-current (My paypal link is documented here https://github.com/ChristopherHX/runner.server/discussions/200#discussioncomment-6641453)
- Thanks to @GameParrot for multiple bug fixes and game update patches not having any known paypal link for me

No collective donations are organized in any way

Current state of this project from my side if it is not completely broken don't fix it. Xbox live related stuff is fragile.

**Comment by MCMrARM** [comment]
Please do not donate to me regarding this project as I do not do any active work with it.

**Comment by ChristopherHX** [comment]
We can close this as no response from pr author, going forward I may or not create an opencollective account for this github organization

_I develop this app for free for now and that only due to mrarm's original work, I would have never started this from scatch thats for shure_

**Pull request closed without merging**
