### PR TITLE
Minecraft Bedrock Launcher needs to be updated

### PR DESCRIPTION
**Pull request by DatOneFunKid123**
Hello,
Just wanted to inform that the Minecraft bedrock launcher should be updated to fit the new 1.19 standards if possible and as soon would be very appreciative.

### CODE REVIEW

**Comment by ChristopherHX** [comment]
Why?
> This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

_1.18.12 works fine_

**Comment by RedsonBr140** [comment]
> Why?
> > This program is distributed in the hope that it will be useful,
>     but WITHOUT ANY WARRANTY; without even the implied warranty of
>     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>     GNU General Public License for more details.
> 
> _1.18.12 works fine_

But what about who wants to play with their friends?

**Comment by Mhowser** [comment]
Chris is the only active developer for this project, if you want an update faster then start here https://www.learncpp.com/

**Comment by hirqkii** [comment]
@Mhowser will chris update the Launcher :-:

**Comment by hirqkii** [comment]
@ChristopherHX Hv you stopped updating the linux launcher? PLEASE UPDATE It i just spent 10 dollars on it :(

**Comment by RedsonBr140** [comment]
> @ChristopherHX Hv you stopped updating the linux launcher? PLEASE UPDATE It i just spent 10 dollars on it :(

As himself said above, this software is distributed WITHOUT ANY WARRANTY, so please  learn C++ if you want a update soon

**Comment by hirqkii** [comment]
@RedsonBr140 how would learning C++ get an update?

**Comment by RedsonBr140** [comment]
@hirqkii you would be able to contribute

**Pull request closed without merging**
